WebApp/WebApp/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Repository;
using WebApp.EFModel;
using WebApp.Interfaces;
using Microsoft.Extensions.Configuration;

namespace WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SearchController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly iMovieRepository _movieRepository;
        private readonly IConfiguration Configuration;

        private const string AuthenticatorUriFormat = "otpauth://totp/{0}:{1}?secret={2}&issuer={0}&digits=6";
        private const string RecoveryCodesKey = nameof(RecoveryCodesKey);

        public SearchController(
          UserManager<ApplicationUser> userManager,
          iMovieRepository movieRepository,
          IConfiguration configuration)
        {
            _userManager = userManager;
            _movieRepository = movieRepository;
            Configuration = configuration;
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Search(string searchQuery, string returnUrl = null)
        {
            int movieCount = Configuration.GetValue<int>("MovieCount");
            List<Classes.Movie> listOutputMovies = new List<Classes.Movie>();
            listOutputMovies.AddRange(_movieRepository.FindNMoviesByTitle(searchQuery, movieCount));
            listOutputMovies.AddRange(_movieRepository.FindNMoviesByGenre(searchQuery, movieCount));

            ViewData["UserQuery"] = searchQuery;
            ViewData["SearchOutputMovieList"] = listOutputMovies;
            return View();
        }
    }
}

WebApp/WebApp/Views/Shared/_ArticleSliderPartial.cshtml
@using WebApp.Classes

@model List<WebApp.Classes.Article>
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        @for (int i = 0; i < Model.Count; i++)
        {
            if (i == 0)
            {
        <li data-target="#myCarousel" data-slide-to="@i" class="active"></li>
            }
            else {
        <li data-target="#myCarousel" data-slide-to="@i" class="active"></li>
            }
        }
    </ol>
    <div class="carousel-inner" role="listbox">
        @for (int i = 0; i < Model.Count; i++)
        {
            if (i == 0)
            {
                @Html.Raw("<div class=\"item active\">")
            }
            else
            {
                @Html.Raw("<div class=\"item\">")
            }
            <img src="@Model[i].ImageLink" alt="@Model[i].Title" class="img-responsive" />
            <div class="carousel-caption half-black" role="option">
                <h3>@Model[i].Title</h3>
                <p>@Model[i].Snippet</p>
            </div>
        @Html.Raw("</div>")
        }
            </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
    </div>

WebApp/WebApp/Views/Shared/_GenresPartial.cshtml
    <option value="Adventure">Przygoda</option>
    <option value="Animation">Animacja</option>
    <option value="Children">Dziecięcy</option>
    <option value="Comedy">Komedia</option>
    <option value="Fantasy">Fantasy</option>
    <option value="Romance">Romans</option>
    <option value="Drama">Dramat</option>
    <option value="Action">Akcja</option>
    <option value="Crime">Kryminał</option>
    <option value="Drama">Dreszczowiec</option>
    <option value="Horror">Horror</option>
    <option value="Mystery">Tajemniczy</option>
    <option value="Sci-Fi">Fantastyczno-Naukowy</option>
    <option value="Documentary">Dokument</option>
    <option value="IMAX">IMAX</option>
    <option value="War">Wojenny</option>
    <option value="Western">Western</option>
    <option value="Film-Noir">Detektywistyczny</option>

WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div id="bodyBackground">
    <div id="bodyCover">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApp</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Strona Główna</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">O nas</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a></li>
                        <li>
    <form asp-controller="Search" asp-action="Search" method="get">
        <input class="rating-select" type="text" name="searchQuery" />
        <button type="submit" class="btn btn-default">Wyszukaj</button>
    </form>
</li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
        </div>
        </div>  
    </div>
    <footer>
        <div>

            <p>&copy; 2018 - WebApp</p>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/WebApp/Views/Shared/_MoviesPartial.cshtml
@using WebApp.Classes

@model List<WebApp.Classes.Movie>

<div class="indexPageMovies row row-eq-height">
    @{
        for (int i = 0; i < Model.Count; i++)
        {
            if (i % 6 == 0 && i != 0)
            {
                @Html.Raw("</div><div class=\"indexPageMovies row row-eq-height\">")
            }
            <div class="col-sm-2 zoom small nopadding" style="background: url('@Model[i].Link'); background-size:100% 100%;">
                <div class="half-black bottom-text">
                    <a href="@Model[i].IMDBLink">
                        <h4>@Model[i].Title</h4>
                    </a>
                    <label>Gatunki: @Model[i].Genres.ToString()</label><br />
                    <label>Średnia ocena: @Model[i].MeanOfRatings.ToString()</label><br />
                    <label>Liczba ocen: @Model[i].NoOfRatings.ToString()</label>
                </div>
            </div>
        }
    }
</div>